version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app/backend
    # command: uvicorn backend.app.main:app --host 0.0.0.4 --port 8000 --reload
    # We will uncomment this when we add a Dockerfile for the backend later.
