import operator
from typing import Annotated, Sequence, TypedDict, List
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """
    The state of the RevPilot Analyst Agent (Single Agent - Step 4).
    """
    user_question: str
    messages: Annotated[Sequence[BaseMessage], operator.add]
    final_answer: str

class MultiAgentState(TypedDict):
    """
    The shared state for the Multi-Agent Investigation Workflow (Step 5).
    Acts as the 'shared investigation notebook'.
    """
    
    # The original question asked by the user
    user_question: str
    
    # The list of general messages in the conversation (if any)
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # The plan generated by the Orchestrator, dictating which agents to run
    investigation_plan: dict
    
    # The agent currently executing (or intended to execute)
    active_agent: str
    
    # Structured findings returned by the Sales Investigator
    sales_findings: dict
    
    # Structured findings returned by the Inventory Investigator
    inventory_findings: dict
    
    # Structured findings returned by the Customer Investigator
    customer_findings: dict
    
    # A dictionary of errors encountered by any of the agents
    agent_errors: dict

    # Structured verifier audit of specialist claims
    verification_results: dict
    
    # The preliminary synthesized answer produced by the Synthesis node
    final_answer: str
