import pandas as pd
from typing import Dict, List, Any
from .data_loader import get_sales_data, get_customers_data

def get_customer_revenue(customer_id: str = None) -> List[Dict[str, Any]]:
    """Get total revenue generated by each customer, or a specific customer."""
    sales = get_sales_data()
    if customer_id:
        sales = sales[sales['customer_id'] == customer_id]
        if sales.empty:
            raise ValueError(f"No sales found for customer_id: {customer_id}")
            
    grouped = sales.groupby('customer_id')['revenue'].sum().reset_index()
    grouped['revenue'] = grouped['revenue'].round(2)
    return grouped.to_dict(orient='records')

def get_customer_order_count(customer_id: str = None) -> List[Dict[str, Any]]:
    """Get total number of orders placed by each customer, or a specific customer."""
    sales = get_sales_data()
    if customer_id:
        sales = sales[sales['customer_id'] == customer_id]
        if sales.empty:
            raise ValueError(f"No sales found for customer_id: {customer_id}")
            
    grouped = sales.groupby('customer_id')['order_id'].nunique().reset_index(name='order_count')
    return grouped.to_dict(orient='records')

def get_revenue_by_customer_segment() -> List[Dict[str, Any]]:
    """Get total revenue broken down by customer segment."""
    sales = get_sales_data()
    customers = get_customers_data()
    df = sales.merge(customers, on='customer_id', how='left')
    grouped = df.groupby('customer_segment')['revenue'].sum().reset_index()
    grouped['revenue'] = grouped['revenue'].round(2)
    return grouped.to_dict(orient='records')

def get_revenue_by_region() -> List[Dict[str, Any]]:
    """Get total revenue broken down by customer location (region)."""
    sales = get_sales_data()
    customers = get_customers_data()
    df = sales.merge(customers, on='customer_id', how='left')
    grouped = df.groupby('location')['revenue'].sum().reset_index()
    grouped['revenue'] = grouped['revenue'].round(2)
    return grouped.to_dict(orient='records')

def compare_customer_activity_between_periods(start_date: str, end_date: str, comparison_start_date: str, comparison_end_date: str) -> List[Dict[str, Any]]:
    """Compare each customer's revenue and order count between two periods."""
    sales = get_sales_data()
    
    mask1 = (sales['order_date'] >= pd.to_datetime(start_date)) & (sales['order_date'] <= pd.to_datetime(end_date))
    mask2 = (sales['order_date'] >= pd.to_datetime(comparison_start_date)) & (sales['order_date'] <= pd.to_datetime(comparison_end_date))
    
    period1 = sales[mask1].groupby('customer_id').agg(current_revenue=('revenue', 'sum'), current_orders=('order_id', 'nunique')).reset_index()
    period2 = sales[mask2].groupby('customer_id').agg(previous_revenue=('revenue', 'sum'), previous_orders=('order_id', 'nunique')).reset_index()
    
    comparison = pd.merge(period2, period1, on='customer_id', how='outer').fillna(0)
    comparison['revenue_change'] = (comparison['current_revenue'] - comparison['previous_revenue']).round(2)
    comparison['current_revenue'] = comparison['current_revenue'].round(2)
    comparison['previous_revenue'] = comparison['previous_revenue'].round(2)
    
    return comparison.to_dict(orient='records')

def identify_declining_customers(start_date: str, end_date: str, comparison_start_date: str, comparison_end_date: str, threshold: float = -100.0) -> List[Dict[str, Any]]:
    """Identify customers whose revenue dropped by more than `threshold` between two periods."""
    comparison = compare_customer_activity_between_periods(start_date, end_date, comparison_start_date, comparison_end_date)
    declining = [c for c in comparison if c['revenue_change'] <= threshold]
    # Sort by largest drop first
    declining.sort(key=lambda x: x['revenue_change'])
    return declining

def identify_high_value_customers(top_n: int = 10) -> List[Dict[str, Any]]:
    """Identify the top N customers by lifetime revenue."""
    revenue = get_customer_revenue()
    # Sort descending by revenue
    revenue.sort(key=lambda x: x['revenue'], reverse=True)
    return revenue[:top_n]
